# -*- coding: utf-8 -*-
"""Slot_Machine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-0zywvJVToc-yX8LFQZWTrU7CtIniKI0
"""

#python Slot Machine
import random
def spin_row():
  symbols=["🍉","🍒" ,"🍋", "🔔","⭐"]
  return[random.choice(symbols) for _ in range(3)] #list comphreshion
                                                   #results=[]
                                                   #for symbol in range(3):
                                                   #  results.append(random.choice(symbols))
                                                   #return result
def print_row(row):
  print("-------------------")
  print(" | ".join(row))
def get_payout(row,bet):
  if row[0] == row[1] == row[2]:
    if row[0] =='🍉':
      return bet * 3
    elif row[0] == '🍒':
      return bet * 4
    elif row[0] == '🍋':
      return bet * 5
    elif row[0] == '🔔':
      return bet * 10
    elif row[0] == '⭐':
      return bet * 20
  return 0
def main():
  balance = 100
  print("--------------------------")
  print("WELCOME TO PYTHON SLOT GAME!")
  print("symbols:🍉 🍒 🍋 🔔 ⭐")                      #to put symbols click (win+;)
  print("-------------------------_-")
  while balance>0:
    print(f"current balance: ${balance}")
    bet=input("Place your bet amount:")

    if not bet.isdigit():
      print("please enter a valid number:")
      continue    #continue will skip the loop and starts from begining

    bet =int(bet)
    if bet > balance:
      print("Insufficient funds")
      continue

    if bet <=0:
      print("Bet must be greater than 0")
      continue
    balance-=bet
    row=spin_row()
    print("Spinning...\n")
    print_row(row)

    payout=get_payout(row,bet)
    if payout>0:
      print(f"you won ${payout}")
    else:
      print("Sorry you lost this round")
    balance += payout

    play_again=input("Do you want spin again?(y/n):").upper()
    if play_again !='Y':
      break
  print("--------------------------")
  print(f"GAME OVER! your final balance is ${balance}")
  print("--------------------------")
if __name__ == '__main__':
  main()